### ISSUE TITLE
Epäselvien lyhenteiden kartoittaminen ja avaus

### ISSUE THREAD

**Issue by tvirolai** [NatLibFi/USEMARCON-RDA#90]
Katsottava, että ambivalentit lyhenteet eivät avaudu mekaanisesti, vaan kielen mukaan. Esim. "ork." --> orkesteri/orkester, "s." --> sivu/sivua/sidor jne. Kuvailukieli yritetään tunnistaa 336-337-kenttien perusteella.

**Comment by AndreasSoderlund** [comment]
Det gäller även t.ex. "ill." som med de nuvarande konverteringsreglerna blir "illustrated" även när det borde bli "illustrerad".

**Comment by chrnelson** [comment]
Toinen esimerkki: rev. tulee nyt englanniksi revised mutta on myös ruotsiksi reviderad (esim. Reviderad och utökad upplaga) tai reviderade (3. reviderade upplagan). Useimmissa Tritonian tietueissa on 336 ja 337 suomeksi vaikka 250-kentässä käytetty kieli voi olla suomi, ruotsi tai englanti...

**Comment by chrnelson** [comment]
ja vielä toinen: tab. on sekä tables että tabeller. Tritoniassa on usein käytetty tab. ruotsinkielisissä opinnäytteissä

**Comment by tvirolai** [comment]
Näyttää siltä, että muut kuin yksiselitteisesti avautuvat lyhenteet on paras jättää käsittelemättä konversiossa. Kuvailukielen päätteleminen tietueesta koneellisesti ei taida käytännössä onnistua turvallisesti.

**Comment by ErkkiHuttunen** [comment]
Mielestäni tätä pitäisi vielä harkita uudelleen hakumuotojen osalta. Ainakin musiikkiaineistossa huomattava osa konversiosta nyt pois jätetyistä lyhenteistä (ork., S, A, T, B, Bar, Mz) liittyy hakumuotoihin (esim. 130, 240, 600, 700), joissa tietueiden kuvailukieltä ei ole tarpeen selvittää. Ratkaisevaa on tietokannan luettelointikieli. Esim. Arscassa 240-kentän "ork." tulee konvertoida aina suomenkieliseen muotoon, koska Arscan luettelointikieli on suomi.

Jos hakumuodoissa olevia lyhenteitä ei tässä konversiossa avata, niin mitä sitten tehdään? Eihän niitä manuaalisestikaan ole mahdollista avata. Eikä avaamattakaan voi jättää, jos RDA:n mukaista kuvailua aiotaan jatkossa tehdä.
